name: user_repository
description: The Repo that handles users
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
 
  firebase_auth: ^4.16.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.6.0
  rxdart: ^0.27.7
  path: ^1.8.3

  user_repository: 
    path:packages/user_repository
  pizza_repository:
    path:packages/pizza_repository
    




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true